import { NextResponse, type NextRequest } from 'next/server';
import { createClient, getSupabaseAdminClient } from '@/utils/supabase/server';
import { verify2FAOTP } from '@/lib/2fa';

const RESERVED_USERNAMES = ['admin', 'support', 'help', 'system', 'official', 'security', 'p2p', 'moderator'];

export async function GET() {
  try {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const admin = getSupabaseAdminClient();
    const { data: profile, error } = await admin
      .from('profiles')
      .select('*')
      .eq('id', user.id)
      .maybeSingle();

    if (error) {
      console.error('Error fetching profile in /api/user/settings:', error);
      return NextResponse.json({ error: 'Failed to retrieve profile' }, { status: 500 });
    }

    // Determine auth provider
    const provider = user.app_metadata?.provider || 
                     (user.identities && user.identities[0]?.provider) || 
                     'email';

    return NextResponse.json({
      user: {
        id: user.id,
        email: user.email,
        auth_provider: provider,
      },
      profile: profile || {
        id: user.id,
        username: user.email?.split('@')[0] || `user_${user.id.slice(0, 6)}`,
        full_name: '',
        country: 'IN',
        preferred_currency: 'USD',
        dob: null,
        name_visibility: 'FULL',
        account_status: 'ACTIVE',
        kyc_status: 'NOT_STARTED',
        is_2fa_enabled: false,
        avatar_url: null,
        photo_url: null,
      }
    });
  } catch (err: any) {
    console.error('GET /api/user/settings unexpected error:', err);
    return NextResponse.json({ error: err.message || 'Internal server error' }, { status: 500 });
  }
}

export async function PATCH(req: NextRequest) {
  try {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await req.json().catch(() => ({}));
    const { field, data } = body;

    if (!field) {
      return NextResponse.json({ error: 'Missing target setting field' }, { status: 400 });
    }

    const admin = getSupabaseAdminClient();

    switch (field) {
      case 'username': {
        const rawUsername = data?.username?.trim().toLowerCase();
        if (!rawUsername || !/^[a-z0-9._]{3,25}$/.test(rawUsername)) {
          return NextResponse.json({
            error: 'Username must be 3-25 characters and contain only lowercase letters, numbers, dots, and underscores.'
          }, { status: 400 });
        }

        if (RESERVED_USERNAMES.includes(rawUsername)) {
          return NextResponse.json({ error: 'This username is reserved by the platform.' }, { status: 400 });
        }

        // Fetch current user profile to enforce one-time username change
        const { data: currentProfile } = await admin
          .from('profiles')
          .select('id, username, username_changed, username_changed_count, username_changes_remaining')
          .eq('id', user.id)
          .single();

        if (
          currentProfile?.username_changed ||
          (currentProfile?.username_changed_count && currentProfile.username_changed_count >= 1) ||
          (currentProfile?.username_changes_remaining !== undefined && currentProfile.username_changes_remaining <= 0)
        ) {
          return NextResponse.json({
            error: 'You can only change your username one time after your autogenerated username. Your handle is permanently locked.'
          }, { status: 400 });
        }

        if (currentProfile?.username && currentProfile.username.toLowerCase() === rawUsername) {
          return NextResponse.json({
            error: 'New username must be different from your current handle.'
          }, { status: 400 });
        }

        // Check if taken by another user
        const { data: existing } = await admin
          .from('profiles')
          .select('id')
          .ilike('username', rawUsername)
          .neq('id', user.id)
          .maybeSingle();

        if (existing) {
          return NextResponse.json({ error: 'This username is already taken by another trader.' }, { status: 409 });
        }

        const { error: updateErr } = await admin
          .from('profiles')
          .update({
            username: rawUsername,
            display_name: rawUsername,
            username_changed: true,
            username_changed_count: 1,
            username_changes_remaining: 0,
            updated_at: new Date().toISOString(),
          })
          .eq('id', user.id);

        if (updateErr) throw updateErr;

        // Implant new username into auth user metadata and P2P ads
        try {
          await admin.auth.admin.updateUserById(user.id, {
            user_metadata: {
              username: rawUsername,
              display_name: rawUsername,
            },
          });
        } catch (authErr) {
          console.warn('Auth metadata update warning:', authErr);
        }

        try {
          await admin.from('p2p_ads').update({
            user_display_name: rawUsername,
          }).eq('user_id', user.id);
        } catch (adsErr) {
          console.warn('P2P ads display_name update warning:', adsErr);
        }

        return NextResponse.json({ success: true, field, updatedValue: rawUsername, message: 'Username updated successfully.' });
      }

      case 'avatar': {
        const avatarUrl = data?.avatarUrl || null;
        const { error: updateErr } = await admin
          .from('profiles')
          .update({
            avatar_url: avatarUrl,
            photo_url: avatarUrl,
            updated_at: new Date().toISOString(),
          })
          .eq('id', user.id);

        if (updateErr) throw updateErr;

        // Implant new avatar into auth metadata
        try {
          await admin.auth.admin.updateUserById(user.id, {
            user_metadata: {
              avatar_url: avatarUrl,
              photo_url: avatarUrl,
              picture: avatarUrl,
              photoURL: avatarUrl,
            },
          });
        } catch (authErr) {
          console.warn('Auth metadata avatar update warning:', authErr);
        }

        return NextResponse.json({ success: true, field, updatedValue: avatarUrl, message: 'Profile picture updated successfully.' });
      }

      case 'personal_info': {
        const { fullName, dob, nameVisibility } = data || {};

        // Check if user has verified KYC documents
        const { data: prof } = await admin
          .from('profiles')
          .select('kyc_status, full_name, dob')
          .eq('id', user.id)
          .maybeSingle();

        const isKycVerified =
          prof?.kyc_status?.toUpperCase() === 'VERIFIED' ||
          prof?.kyc_status?.toUpperCase() === 'APPROVED';

        if (isKycVerified && (fullName !== undefined || dob !== undefined)) {
          return NextResponse.json(
            { error: 'Your legal name and date of birth are permanently locked once KYC verification is approved.' },
            { status: 400 }
          );
        }

        const updates: any = {
          name_visibility: nameVisibility || 'FULL',
          updated_at: new Date().toISOString(),
        };

        // If KYC is not verified, allow updating with duplicate identity check
        if (!isKycVerified) {
          const targetName = (fullName !== undefined ? fullName : prof?.full_name)?.trim();
          const targetDob = (dob !== undefined ? dob : prof?.dob)?.trim();

          if (targetName && targetDob) {
            // Check for duplicate profile
            const { data: duplicateProfiles } = await admin
              .from('profiles')
              .select('id, full_name, dob, date_of_birth')
              .neq('id', user.id)
              .neq('status', 'deleted');

            const match = (duplicateProfiles || []).find((p: any) => {
              const pName = (p.full_name || '').trim().toLowerCase();
              const pDob = (p.dob || p.date_of_birth || '').trim();
              return pName && pDob && pName === targetName.toLowerCase() && pDob === targetDob;
            });

            if (match) {
              // Suspend user for duplicate identity violation
              await admin
                .from('profiles')
                .update({
                  status: 'suspended',
                  is_suspended: true,
                  suspension_reason: `Duplicate identity violation: Attempted to set legal name ("${targetName}") and DOB ("${targetDob}") matching existing user (${match.id}).`,
                  updated_at: new Date().toISOString(),
                })
                .eq('id', user.id);

              return NextResponse.json(
                {
                  error: 'Duplicate Identity Violation: An account with this legal name and date of birth is already registered. Your account has been suspended.',
                  suspended: true,
                },
                { status: 403 }
              );
            }
          }

          if (fullName !== undefined) {
            updates.full_name = fullName?.trim() || null;
          }
          if (dob !== undefined) {
            if (dob) {
              const birthDate = new Date(dob);
              if (!isNaN(birthDate.getTime())) {
                const today = new Date();
                let age = today.getFullYear() - birthDate.getFullYear();
                const m = today.getMonth() - birthDate.getMonth();
                if (m < 0 || (m === 0 && today.getDate() < birthDate.getDate())) {
                  age--;
                }
                if (age < 18) {
                  return NextResponse.json({
                    error: 'No minors allowed: You must be at least 18 years old to trade on PaxOnes.',
                    isMinor: true,
                  }, { status: 400 });
                }
              }
            }
            updates.dob = dob || null;
            updates.date_of_birth = dob || null;
          }
        }

        const { error: updateErr } = await admin
          .from('profiles')
          .update(updates)
          .eq('id', user.id);

        if (updateErr) throw updateErr;

        return NextResponse.json({
          success: true,
          field,
          message: isKycVerified
            ? 'Privacy preference saved. Note: Name and DOB are locked by your verified KYC documents.'
            : 'Personal information saved successfully.'
        });
      }

      case 'country': {
        const newCountry = data?.country?.trim().toUpperCase();
        if (!newCountry || newCountry.length < 2) {
          return NextResponse.json({ error: 'Invalid country code' }, { status: 400 });
        }

        // Check if country is locked by verified KYC
        const { data: prof } = await admin
          .from('profiles')
          .select('is_country_locked, kyc_status')
          .eq('id', user.id)
          .single();

        if (prof?.is_country_locked || prof?.kyc_status === 'APPROVED') {
          return NextResponse.json({
            error: 'Your country is locked to your verified identity document. Contact support for assistance.'
          }, { status: 403 });
        }

        const { error: updateErr } = await admin
          .from('profiles')
          .update({
            country: newCountry,
            updated_at: new Date().toISOString(),
          })
          .eq('id', user.id);

        if (updateErr) throw updateErr;

        return NextResponse.json({ success: true, field, updatedValue: newCountry, message: 'Country updated successfully.' });
      }

      case 'currency': {
        const currency = data?.currency?.trim().toUpperCase() || 'USD';
        const { error: updateErr } = await admin
          .from('profiles')
          .update({
            preferred_currency: currency,
            updated_at: new Date().toISOString(),
          })
          .eq('id', user.id);

        if (updateErr) throw updateErr;

        return NextResponse.json({ success: true, field, updatedValue: currency, message: 'Preferred currency updated.' });
      }

      case 'security_question': {
        const { question, answer, code } = data || {};
        if (!question?.trim()) {
          return NextResponse.json({ error: 'Question cannot be empty' }, { status: 400 });
        }

        // Check if 2FA is enabled; if so, require 2FA OTP verification
        const { data: currentProf } = await admin
          .from('profiles')
          .select('is_2fa_enabled, is_mfa_enabled, two_factor_secret, security_answer_hash')
          .eq('id', user.id)
          .maybeSingle();

        const is2faActive = Boolean(currentProf?.is_2fa_enabled || currentProf?.is_mfa_enabled);
        const userSecret = currentProf?.two_factor_secret || currentProf?.security_answer_hash;

        if (is2faActive) {
          const cleanCode = code ? code.toString().trim() : '';
          if (!cleanCode || !/^\d{4,8}$/.test(cleanCode)) {
            return NextResponse.json({
              error: 'Security Enforcement: 4-8 digit 2FA OTP code is required to modify security questions.',
              requires2FA: true,
            }, { status: 400 });
          }

          const isValid = verify2FAOTP(userSecret, cleanCode, true);
          if (!isValid) {
            return NextResponse.json({
              error: 'Invalid 2FA authentication code.',
              requires2FA: true,
            }, { status: 401 });
          }
        }

        const updates: any = {
          security_question: question.trim(),
          updated_at: new Date().toISOString(),
        };

        if (answer?.trim()) {
          // Simple hash representation or direct secure marker
          updates.security_answer_hash = Buffer.from(answer.trim().toLowerCase()).toString('base64');
        }

        const { error: updateErr } = await admin
          .from('profiles')
          .update(updates)
          .eq('id', user.id);

        if (updateErr) throw updateErr;

        return NextResponse.json({ success: true, field, message: 'Security question saved successfully.' });
      }

      case 'two_factor': {
        const enabled = Boolean(data?.enabled);
        const code = data?.code?.toString().trim();
        const secret = data?.secret?.toString().trim();

        const { data: currentProf } = await admin
          .from('profiles')
          .select('is_2fa_enabled, is_mfa_enabled, two_factor_secret, security_answer_hash')
          .eq('id', user.id)
          .maybeSingle();

        const is2faActive = Boolean(currentProf?.is_2fa_enabled || currentProf?.is_mfa_enabled);
        const existingSecret = currentProf?.two_factor_secret || currentProf?.security_answer_hash;

        if (enabled) {
          if (!code || !/^\d{4,8}$/.test(code)) {
            return NextResponse.json({
              error: 'Invalid authenticator code. Please enter a valid 4-8 digit OTP code shown in your authenticator app.'
            }, { status: 400 });
          }
          const validSecret = secret || existingSecret;
          if (validSecret) {
            const isValid = verify2FAOTP(validSecret, code, true);
            if (!isValid) {
              return NextResponse.json({
                error: 'Invalid authenticator code. Please check the time on your device and try again.'
              }, { status: 400 });
            }
          }
        } else {
          // Mandatory 2FA OTP verification when disabling 2FA
          if (is2faActive) {
            if (!code || !/^\d{4,8}$/.test(code)) {
              return NextResponse.json({
                error: 'Security Enforcement: Please enter your 4-8 digit Authenticator OTP to confirm disabling 2FA.',
                requires2FA: true,
              }, { status: 400 });
            }
            if (existingSecret) {
              const isValid = verify2FAOTP(existingSecret, code, true);
              if (!isValid) {
                return NextResponse.json({
                  error: 'Invalid authenticator OTP code.',
                  requires2FA: true,
                }, { status: 401 });
              }
            }
          }
        }

        const updates: any = {
          is_2fa_enabled: enabled,
          is_mfa_enabled: enabled,
          updated_at: new Date().toISOString(),
        };

        if (enabled && secret) {
          updates.two_factor_secret = secret;
        } else if (!enabled) {
          updates.two_factor_secret = null;
        }

        const { error: updateErr } = await admin
          .from('profiles')
          .update(updates)
          .eq('id', user.id);

        if (updateErr) throw updateErr;

        return NextResponse.json({
          success: true,
          field,
          updatedValue: enabled,
          message: enabled ? 'Two-Factor Authentication verified and activated.' : 'Two-Factor Authentication disabled.'
        });
      }

      case 'preferences': {
        const { language, timezone, autoReplyMessage, notifications } = data || {};
        const updates: any = {
          updated_at: new Date().toISOString(),
        };

        if (language !== undefined) updates.preferred_language = language;
        if (timezone !== undefined) updates.timezone = timezone;
        if (autoReplyMessage !== undefined) updates.auto_reply_message = autoReplyMessage;
        if (notifications !== undefined) updates.notifications_preferences = notifications;

        try {
          await admin
            .from('profiles')
            .update(updates)
            .eq('id', user.id);
        } catch (prefErr) {
          console.warn('Preferences profile update error:', prefErr);
        }

        return NextResponse.json({
          success: true,
          field,
          message: 'Preferences saved successfully.'
        });
      }

      case 'password': {
        const { newPassword, code } = data || {};
        if (!newPassword || newPassword.length < 8) {
          return NextResponse.json({ error: 'Password must be at least 8 characters.' }, { status: 400 });
        }

        // 2FA check
        const { data: currentProf } = await admin
          .from('profiles')
          .select('is_2fa_enabled, is_mfa_enabled, two_factor_secret, security_answer_hash')
          .eq('id', user.id)
          .maybeSingle();

        const is2faActive = Boolean(currentProf?.is_2fa_enabled || currentProf?.is_mfa_enabled);
        const userSecret = currentProf?.two_factor_secret || currentProf?.security_answer_hash;

        if (is2faActive) {
          const cleanCode = code ? code.toString().trim() : '';
          if (!cleanCode || !/^\d{4,8}$/.test(cleanCode)) {
            return NextResponse.json({
              error: 'Security Enforcement: 4-8 digit 2FA OTP code is required to change your password.',
              requires2FA: true,
            }, { status: 400 });
          }

          if (userSecret) {
            const isValid = verify2FAOTP(userSecret, cleanCode, true);
            if (!isValid) {
              return NextResponse.json({
                error: 'Invalid 2FA authentication code.',
                requires2FA: true,
              }, { status: 401 });
            }
          }
        }

        const { error: pwErr } = await admin.auth.admin.updateUserById(user.id, {
          password: newPassword,
        });

        if (pwErr) {
          return NextResponse.json({ error: pwErr.message }, { status: 400 });
        }

        return NextResponse.json({
          success: true,
          field,
          message: 'Password updated successfully.'
        });
      }

      case 'kyc_submission': {
        const { documentType, country, street, city, postalCode, documentNumber } = data || {};
        if (!documentType || !country) {
          return NextResponse.json({ error: 'Document type and country are required.' }, { status: 400 });
        }

        const updates: any = {
          kyc_status: 'PENDING',
          country: country.trim().toUpperCase(),
          updated_at: new Date().toISOString(),
        };

        if (street) updates.address_street = street.trim();
        if (city) updates.address_city = city.trim();
        if (postalCode) updates.address_postal_code = postalCode.trim();

        const { error: updateErr } = await admin
          .from('profiles')
          .update(updates)
          .eq('id', user.id);

        if (updateErr) throw updateErr;

        return NextResponse.json({
          success: true,
          field,
          message: 'Identity & Address verification details submitted successfully. Status is now PENDING review.'
        });
      }

      default: {
        return NextResponse.json({
          success: true,
          field,
          message: `${field} preference updated.`
        });
      }
    }
  } catch (err: any) {
    console.error('PATCH /api/user/settings unexpected error:', err);
    return NextResponse.json({ error: err.message || 'Failed to update setting' }, { status: 500 });
  }
}
