import Link from 'next/link';
import { ArrowLeft, Gavel, Scale, AlertCircle, FileCheck, CheckCircle2, ShieldCheck, Clock } from 'lucide-react';
import { Button } from '@/components/ui/button';

export const metadata = {
  title: 'Dispute Resolution Guide | Paxones Guides',
  description: 'How disputes work, evidence submission guidelines, moderator arbitrations, and timelines on Paxones P2P.',
};

export default function DisputeResolutionGuidePage() {
  return (
    <div className="max-w-4xl mx-auto py-8 px-4 sm:px-6">
      <div className="mb-8">
        <Link href="/guides" className="inline-flex items-center text-sm font-medium text-emerald-600 hover:text-emerald-500 dark:text-emerald-400 gap-1.5 transition-colors">
          <ArrowLeft className="h-4 w-4" /> Back to Guides & Safety Hub
        </Link>
      </div>

      <div className="border-b border-slate-200 dark:border-[#1e2640] pb-8 mb-8">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-semibold bg-purple-100 text-purple-800 dark:bg-purple-950/60 dark:text-purple-300 mb-4">
          <Gavel className="h-3.5 w-3.5" /> Guide 05 • Fair Arbitration
        </div>
        <h1 className="text-3xl sm:text-4xl font-black tracking-tight text-slate-900 dark:text-white">
          Dispute Resolution & Mediation
        </h1>
        <p className="mt-3 text-lg text-slate-600 dark:text-slate-300 leading-relaxed">
          How our trained 24/7 compliance and dispute specialists arbitrate disagreements fairly, impartially, and transparently.
        </p>
      </div>

      <div className="space-y-8 text-slate-700 dark:text-slate-300 leading-relaxed">
        {/* When to open a dispute */}
        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-slate-900 dark:text-white flex items-center gap-2">
            <Scale className="h-6 w-6 text-purple-600" /> When Should You Open a Dispute?
          </h2>
          <p>
            You should open a dispute whenever a trade cannot proceed normally through good-faith communication between buyer and seller. Common legitimate reasons include:
          </p>
          <div className="grid sm:grid-cols-2 gap-4 pt-1">
            <div className="p-4 rounded-xl border border-slate-200 dark:border-[#1e2640] bg-slate-50 dark:bg-[#101726]">
              <h4 className="font-bold text-slate-900 dark:text-white text-sm">For Buyers:</h4>
              <ul className="text-xs space-y-1.5 text-slate-600 dark:text-slate-400 mt-2 list-disc list-inside">
                <li>You paid the seller in full, but the seller is unresponsive or refuses to release.</li>
                <li>The seller claimed they never received the money despite valid bank confirmation.</li>
                <li>The seller requested you cancel after payment was initiated.</li>
              </ul>
            </div>

            <div className="p-4 rounded-xl border border-slate-200 dark:border-[#1e2640] bg-slate-50 dark:bg-[#101726]">
              <h4 className="font-bold text-slate-900 dark:text-white text-sm">For Sellers:</h4>
              <ul className="text-xs space-y-1.5 text-slate-600 dark:text-slate-400 mt-2 list-disc list-inside">
                <li>The buyer clicked 'I have paid' but no funds have arrived in your account.</li>
                <li>The payment arrived with conflicting or unverified reference details.</li>
                <li>The payment was underpaid or received through an unapproved method.</li>
              </ul>
            </div>
          </div>
        </section>

        {/* Evidence Guidelines */}
        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-slate-900 dark:text-white flex items-center gap-2">
            <FileCheck className="h-6 w-6 text-purple-600" /> Accepted Evidence & Documentation
          </h2>
          <p>
            When a dispute is active, both parties can present verifiable proof in the dispute chat. To ensure your case is resolved in your favor, provide:
          </p>
          <ul className="list-disc list-inside space-y-2 pl-2 text-sm text-slate-600 dark:text-slate-400">
            <li><strong>Official Bank Statement (PDF):</strong> Full account statement showing the date, amount, reference number, sender name, and recipient name.</li>
            <li><strong>Unedited Screen Recordings:</strong> Video showing you logging in to your banking application, showing account balance, and displaying recent transaction logs.</li>
            <li><strong>UTR / Transaction Reference ID:</strong> The official reference number generated by the banking network (IMPS, UPI, NEFT, SEPA, Fedwire).</li>
          </ul>
        </section>

        {/* Moderator Workflow */}
        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-slate-900 dark:text-white flex items-center gap-2">
            <ShieldCheck className="h-6 w-6 text-purple-600" /> How Moderators Decide Outcomes
          </h2>
          <div className="p-5 rounded-2xl border border-purple-200 dark:border-purple-900/40 bg-purple-50/40 dark:bg-purple-950/20 space-y-3">
            <p className="text-sm text-purple-950 dark:text-purple-200">
              Moderators review the complete history of the trade: terms agreed upon, payment instructions, message logs, submitted documents, and bank validation.
            </p>
            <div className="grid sm:grid-cols-2 gap-3 text-xs pt-1">
              <div className="p-3 bg-white dark:bg-[#101726] rounded-xl border border-purple-100 dark:border-purple-900/40">
                <span className="font-bold text-emerald-600 block mb-1">Crypto Awarded to Buyer:</span>
                When definitive evidence proves fiat funds were legitimately transferred and received by the seller.
              </div>
              <div className="p-3 bg-white dark:bg-[#101726] rounded-xl border border-purple-100 dark:border-purple-900/40">
                <span className="font-bold text-blue-600 block mb-1">Crypto Returned to Seller:</span>
                When the buyer fails to provide valid proof within the allotted evidence window, or payment was fraudulent/chargebacked.
              </div>
            </div>
          </div>
        </section>

        <div className="pt-6 border-t border-slate-200 dark:border-[#1e2640] flex justify-between items-center">
          <Link href="/guides/escrow" className="text-sm text-slate-500 hover:text-slate-800 dark:hover:text-slate-200">
            ← Guide 04: Understanding Escrow
          </Link>
          <Link href="/guides/reputation">
            <Button className="bg-emerald-600 hover:bg-emerald-700 text-white font-semibold">
              Read Next: Building Reputation →
            </Button>
          </Link>
        </div>
      </div>
    </div>
  );
}
